name: CDK Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build CDK
        run: npm run build

      - name: Deploy CDK
        env:
          AWS_REGION: us-west-2
          AWS_ACCOUNT_ID: 918911652037
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm install -g aws-cdk
          cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION
          cdk deploy --require-approval never
